name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          path: tachimawari

      - name: Checkout Tachimawari Interfaces
        uses: actions/checkout@v4.1.1
        with:
          repository: ichiro-its/tachimawari_interfaces
          path: tachimawari_interfaces

      - name: Checkout Kansei Interfaces
        uses: actions/checkout@v4.1.1
        with:
          repository: ichiro-its/kansei_interfaces
          path: kansei_interfaces

      - name: Checkout Keisan
        uses: actions/checkout@v4.1.1
        with:
          repository: ichiro-its/keisan
          path: keisan

      - name: Checkout Jitsuyo
        uses: actions/checkout@v4.1.1
        with:
          repository: ichiro-its/jitsuyo
          path: jitsuyo
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup workspace
        uses: ichiro-its/ros2-ws-action/setup@v1.0.1

      - name: Build workspace
        uses: ichiro-its/ros2-ws-action/build@v1.0.1

      - name: Test workspace
        uses: ichiro-its/ros2-ws-action/test@v1.0.1
