name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: tachimawari

      - name: Build and test workspace
        uses: ichiro-its/ros2-build-and-test-action@main
